server:
  port: 9296
spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: git@github.com:emmanuel-mutua/spring-microservice-app-config.git
          clone-on-start: true
        native:
          search-locations: classpath:/configurations
  profiles:
    active: native
#    use native active profile

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true