#CENRTALIZE EXTERNAL CONFIGURATIONS IN ONE CONFIG FILE
server:
  port: 9296
spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: git@github.com:emmanuel-mutua/spring-microservice-app-config.git
          clone-on-start: true
#          Tell spring that this also includes config files in the local filesystem
        native:
          search-locations: classpath:/configurations
  profiles:
    active: native