server:
  port: 8087
eureka:
  client:
    register-with-eureka: false
spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
#      mvc:
#        routes:
#          - id: product
#            uri: http://localhost:8085
#            predicates:
#              - Path=/product/**
#          - id: order
#            uri: http://localhost:8081
#            predicates:
#              - Path=/order/**
#          - id: payment
#            uri: http://localhost:8082
#            predicates:
#              - Path=/payment/**

  eureka:
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
    instance:
      prefer-ip-address: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/product-order-py-ms-realm

management:
  tracing:
    sampling:
      probability: 1.0
logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: DEBUG
    reactor:
      netty: DEBUG

keycloak:
  credentials:
    client-secret: mNZIiTfLeh1cMw9KjkJkvCLqZS8WnRAh
    token-endpoint: http://localhost:9090/realms/product-order-py-ms-realm/protocol/openid-connect/token

