server:
  port: 8087
eureka:
  client:
    register-with-eureka: false
spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: product
            uri: http://localhost:8085
            predicates:
              - Path=/product/**
          - id: order
            uri: http://localhost:8081
            predicates:
              - Path=/order/**
          - id: payment
            uri: http://localhost:8082
            predicates:
              - Path=/payment/**
    config:
      discovery:
        enabled: true
  config:
    import: configserver:http://localhost:9296