server:
  port: 8081

spring:
  application:
    name: orderservice

  r2dbc:
    username: postgres
    password: postgres
    url: r2dbc:postgresql://localhost:5433/postgres

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  eureka:
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
    instance:
      prefer-ip-address: true

resilience4j:
  thread-pool-bulkhead:
    backends:
        orderservice:
              max-thread-pool-size: 1 #means only a single thread can be used at a time
              core-thread-pool-size: 1 #pool wiill always have atleast one thread
  bulkhead:
    instances:
      orderservice:
        max-concurrent-calls: 10
