spring:
  application:
    name: orderservice
  config:
    import: configserver:http://localhost:9296
resilience4j:
  thread-pool-bulkhead:
    backends:
        orderservice:
              max-thread-pool-size: 1 #means only a single thread can be used at a time
              core-thread-pool-size: 1 #pool wiill always have atleast one thread
  bulkhead:
    instances:
      orderservice:
        max-concurrent-calls: 10
