spring:
  application:
    name: productservice

  r2dbc:
    username: postgres
    password: postgres
    url: r2dbc:postgresql://localhost:5433/postgres

  flyway:
    enabled: true
    locations: classpath:db/migration

  eureka:
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
    instance:
      prefer-ip-address: true

server:
  port: 8085

management:
  tracing:
    sampling:
      probability: 1.0

